### ISSUE TITLE
Link to geogram - now on github

### ISSUE THREAD

**Issue by BrunoLevy** [MoiseRousseau/SALOME-Voronoi#4]
Hello,

Just to tell you that Geogram is now on github:
https://github.com/BrunoLevy/geogram
(you can update the link in the documentation, and directly link it as a git submodule if it makes things easier)

Best wishes,
-- Bruno

**Comment by MoiseRousseau** [comment]
Hi Bruno,
Thanks for the information, I will update the README soon!
Moise
