### ISSUE TITLE
Polyhedral cell missed when exporting to UNV

### ISSUE THREAD

**Issue by unilord541** [MoiseRousseau/SALOME-Voronoi#7]
When trying to export a polyhedral mesh to UNV, the following warning is received:

During export mesh with name "Mesh_1_Voronoi" to UNV Polyhedrons will be missed.
Do you want to continue?

If click yes, then using the option "ideasUNVtoFoam" from OpenFOAM, and check mesh metrics afterwards, huge mesh openness and volume are detected (>1e300), and there is no mesh to display in paraview.

**Comment by MoiseRousseau** [comment]
The UNV format does not seem to handle polyhedrons, so the Voronoi cells are not exported. This is probably why you can't see anything in Paraview.

**Comment by MoiseRousseau** [comment]
Also, mesh export is a functionnality of Salome, not of the SALOME-Voronoi plugin. Maybe you could have a look at dedicated Salome / OpenFOAM mesh exporter plugin such as https://github.com/oseen/salomeToOpenFOAM

**Comment by unilord541** [comment]
Ok will have a look at them. Thank you!
